force-app/main/default/objects/Product2/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area (square meters)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Balcony__c.field-meta.xml
<CustomField>
    <fullName>Balcony__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balcony</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Swimming_Pool__c.field-meta.xml
<CustomField>
    <fullName>Swimming_Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Swimming Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Apartment.recordType-meta.xml
<RecordType>
    <fullName>Apartment</fullName>
    <active>true</active>
    <label>Apartment</label>
</RecordType>

force-app/main/default/classes/RE_searchEngineProductControllerTest.cls
@isTest
public with sharing class RE_searchEngineProductControllerTest {
    public static final String PREMISE_NAME = 'Apartment';
    public static final String SAMPLE_PRICEBOOK = 'sample_Pricebook2';
    public static final String SAMPLE_PRODUCT = 'sample_Product2';

    @isTest
    static void shouldReturnUserRoleName() {
        String typeOfUser;
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = new User(
            Alias = 'standt',
            Email = 'standarduser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = uniqueUserName
        );

        System.runAs(u) {
            Test.startTest();
            typeOfUser = RE_searchEngineProductController.checkUserPremissions();
            Test.stopTest();
        }
        System.assertEquals(typeOfUser, 'Apartment');
    }

    @isTest
    static void shouldReturnFilteredProducts() {
        List<Product2> foundProductsByFilters = new List<Product2>();
        String stringifiedFilters = '{"Filters_Checkbox_Group":["Swimming Pool","Balcony"]}';

        Id recordType = Schema.SObjectType.Product2.getRecordTypeInfosByName().get(PREMISE_NAME).getRecordTypeId();

        Product2 product1 = new Product2(
            Name = 'Premise1',
            Street__c = 'Nowacka 11',
            City__c = 'B',
            Picture__c = 'AAA',
            Country__c = 'Poland',
            RecordTypeId = recordType,
            Swimming_Pool__c = true,
            Balcony__c = true,
            Area__c = 123
        );
        insert product1;

        List<Pricebook2> pricebooks = Test.loadData(Pricebook2.sObjectType, SAMPLE_PRICEBOOK);
        Pricebook2 pricebook = (Pricebook2) pricebooks[0];

        Test.startTest();
        foundProductsByFilters = RE_searchEngineProductController.searchProductByFilters('', stringifiedFilters);
        Test.stopTest();
        System.assertEquals(foundProductsByFilters[0].Name, 'Premise1');
    }

    @isTest
    static void shouldReturnProductsPrices() {
        List<PricebookEntry> productsPrices = new List<PricebookEntry>();
        String stringifiedFilters = '{"Filters_Checkbox_Group":["Swimming Pool","Balcony"]}';

        Id recordType = Schema.SObjectType.Product2.getRecordTypeInfosByName().get(PREMISE_NAME).getRecordTypeId();

        Product2 product1 = new Product2(
            Name = 'Premise1',
            Street__c = 'Nowacka 11',
            City__c = 'B',
            Picture__c = 'AAA',
            Country__c = 'Poland',
            RecordTypeId = recordType,
            Swimming_Pool__c = true,
            Balcony__c = true,
            Area__c = 123
        );
        insert product1;

        List<Pricebook2> pricebooks = Test.loadData(Pricebook2.sObjectType, SAMPLE_PRICEBOOK);
        Pricebook2 pricebook = (Pricebook2) pricebooks[0];
        System.debug(pricebook);

        Id pricebookId = Test.getStandardPricebookId();
        
        insert new PriceBookEntry(Product2Id = product1.Id, Pricebook2Id = pricebookId, UnitPrice = 30);
        
        Test.startTest();
        productsPrices = RE_searchEngineProductController.getProductsPrice();
        Test.stopTest();

        System.debug(productsPrices);
        System.debug(productsPrices[0]);

        System.assertNotEquals(1, 0);
    }
}